### ISSUE TITLE
What all Packages do I need to install?

### ISSUE THREAD

**Issue by Dhruva-Ananth** [bilalmirza74/folio#2]
Hi, I wish to know the exact process of using this as a template to develop a website, are there any additional packages that I need to install other than the ones guided in this: https://www.youtube.com/watch?v=0fYi8SGA20k

**Comment by bilalmirza74** [comment]
You can refer packages/dependencies here ==> [package.json](https://github.com/bilalmirza74/folio/blob/e2d40c501e0a225df4a4b30e827b228cebf8a848/package.json)

and the add on library was this 
https://www.npmjs.com/package/react-intersection-observer


npm install react-intersection-observer
# or
yarn add react-intersection-observer
